Repository milantru/prankweb, pull requests merged in 2025-05, with the labels that each got.

#31 30 create mapping from ccd
  demos/ccd/create_mapping.py
  demos/ccd/requirements.txt
  src/containers/data-source-executors/executor-p2rank/mapping.json
  src/containers/data-source-executors/executor-p2rank/post_processor.py
Labels: Work done

#65 Ai docker
  .gitattributes
  .gitignore
  src/containers/converter/converter.py
  src/containers/data-source-executors/executor-plm/Dockerfile
  src/containers/data-source-executors/executor-plm/celery_plm.py
  src/containers/data-source-executors/executor-plm/celery_worker.py
  src/containers/data-source-executors/executor-plm/model.py
  src/containers/data-source-executors/executor-plm/models/model_e10.pth
  src/containers/data-source-executors/executor-plm/plm_executor.py
  src/containers/data-source-executors/executor-plm/post_processor.py
  src/containers/data-source-executors/executor-plm/predict.py
  src/containers/data-source-executors/executor-plm/requirements.in
  src/containers/data-source-executors/executor-plm/requirements.txt
  src/containers/data-source-executors/executor-plm/run_executor.py
  src/containers/data-source-executors/executor-plm/train.py
  src/containers/metatask/metatask.py
  src/containers/monitoring/vector.yaml
  src/docker-compose-plankweb.yml
  src/docker-compose.test.yml
  src/docker-compose.yml
  testing/README.md
  testing/files/chains_json_format.json
  testing/plankweb-tests.py
Labels: work in progress

#72 Display linking
  src/containers/conservation/Dockerfile
  src/containers/conservation/conservation.py
  src/containers/converter/converter.py
  src/containers/data-source-executors/data_format/builder.py
  src/containers/data-source-executors/executor-foldseek/Dockerfile
  src/containers/data-source-executors/executor-foldseek/foldseek_executor.py
  src/containers/data-source-executors/executor-foldseek/post_processor.py
  src/containers/data-source-executors/executor-p2rank/Dockerfile
  src/containers/data-source-executors/executor-p2rank/p2rank_executor.py
  src/containers/data-source-executors/executor-p2rank/post_processor.py
  src/containers/data-source-executors/executor-plm/Dockerfile
  src/containers/data-source-executors/executor-plm/plm_executor.py
  src/containers/metatask/metatask.py
  src/containers/shared/status_manager.py
  src/frontend/index.css
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/pages/analytical-page/AnalyticalPage.tsx
  src/frontend/src/pages/analytical-page/AnalyticalPage.tsx.css
  src/frontend/src/pages/analytical-page/components/ErrorMessageBox.tsx
  src/frontend/src/pages/analytical-page/components/MolstarWrapper.tsx
  src/frontend/src/pages/analytical-page/components/RcsbSaguaro.tsx
  src/frontend/src/pages/analytical-page/components/SettingsPanel.tsx
  src/frontend/src/pages/analytical-page/components/Switch.tsx
  src/frontend/src/pages/home/components/InputUserFileBlock.tsx
  src/frontend/src/shared/helperFunctions/typeChecking.ts
  src/frontend/src/shared/services/apiCalls.ts
  src/swagger.yaml
  testing/files/chains_json_format.json
  testing/plankweb-tests.py
Labels: enhancement, Work done
